CREATE TABLE SignedUser(
	uid		BIGINT PRIMARY KEY AUTO_INCREMENT,
	userId	VARCHAR(20) NOT NULL,
	passwd	VARCHAR(20) NOT NULL,
	userName	VARCHAR(20) NOT NULL,
	ssn	VARCHAR(20) NOT NULL,
	email	VARCHAR(20) NOT NULL,
	addr	VARCHAR(20) NOT NULL,
) AUTO_INCREMENT = 1001;

SELECT * FROM SignedUser;